name: Twitter_SearchBot_V3
channels:
  - conda-forge
dependencies:
  - python
  - time
  - numpy
  - json
  - pip
  - pip:
    # - numpy
    - pandas
    - matplotlib
    - requests
    # - json
    # - yfinance
    # - pytrends
    # - demjson
  
  # # - os
  # - json
  # - pandas as pd
  # - matplotlib.pyplot as plt
  # - yfinance as yf
  # - pytrends.requests.TrendReq as TrendReq

  # - demjson
  # # - matplotlib.animation as animation
  # - time.sleep as sleep