name: Twitter_SearchBot_V3
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  - pip:
    # - numpy
    - pandas
    - matplotlib
    # - matplotlib.pyplot as plt
    # - matplotlib.animation as animation
    
  # - requests
  # # - os
  # - json
  # - pandas as pd
  # - matplotlib.pyplot as plt
  # - yfinance as yf
  # - pytrends.requests.TrendReq as TrendReq

  # - demjson
  # # - matplotlib.animation as animation
  # - time.sleep as sleep